/**
 * Generated Supabase database types.
 *
 * HARD RULE (PRD §12.1): this file is generated by running:
 *   npx supabase gen types typescript --local > src/lib/supabase/types.ts
 *
 * Run this after EVERY migration. Committing a migration without regenerating
 * types silently desynchronises the type layer from the schema.
 *
 * Placeholder until the first migration is created.
 */

// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export type Database = {};
